services:
  app-react:
    image: andrenextu/react:1.0.1
    ports:
      - "80:80"
    depends_on:
      - app-java
  app-java:
    image: andrenextu/app-java:1.0.5
    depends_on:
      - mongodb
    ports:
      - "8088:8088"
    volumes:
      - myapp-java:/data
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - REACT_HOST=localhost
      - REACT_PORT=80
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
volumes:
  myapp-java: