spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: storage
nextu:
  filestore: /Users/nolan/Documents/WEBTECH COURS/SpringBoot/storage/filestore
  app:
    jwtSecret: xhxhh137373uddjshkjqshfkjqhkfhilieufizefhiu
    jwtExpirationMs: 86400000
server:
  port: 8088
react:
  host: ${REACT_HOST:}
